### ISSUE TITLE
TypeError: data.reduce is not a function

### ISSUE THREAD

**Issue by ydesgagn** [KeitaMoromizato/textlint-rule-ja-yahoo-kousei#12]
Hi,

I'm using the sample code to transfer data. The schema is properly transferred to big query for all tables. When the code try to insert the first data row, I always get this:

TypeError: data.reduce is not a function
    at MySQLtoBigQuery._toTSV (/Users/yves/Downloads/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:135:41)
    at /Users/yves/Downloads/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:126:34
    at wrappedMapper (/Users/yves/Downloads/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/yves/Downloads/node_modules/map-stream/index.js:96:21)
    at Readable.ondata (/Users/yves/Downloads/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at readableAddChunk (/Users/yves/Downloads/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Readable.push (/Users/yves/Downloads/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Query.<anonymous> (/Users/yves/Downloads/node_modules/mysql/lib/protocol/sequences/Query.js:206:17)
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: data.reduce is not a function
    at MySQLtoBigQuery._toTSV (/Users/yves/Downloads/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:135:41)
    at /Users/yves/Downloads/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:126:34
    at wrappedMapper (/Users/yves/Downloads/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/yves/Downloads/node_modules/map-stream/index.js:96:21)
    at Readable.ondata (/Users/yves/Downloads/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at readableAddChunk (/Users/yves/Downloads/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Readable.push (/Users/yves/Downloads/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Query.<anonymous> (/Users/yves/Downloads/node_modules/mysql/lib/protocol/sequences/Query.js:206:17)
    --------------------
    at Protocol._enqueue (/Users/yves/Downloads/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/yves/Downloads/node_modules/mysql/lib/Connection.js:214:25)
    at /Users/yves/Downloads/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:125:27
    at MySQLtoBigQuery._insertRecords (/Users/yves/Downloads/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:117:14)
    at /Users/yves/Downloads/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:71:25
    at process._tickCallback (internal/process/next_tick.js:103:7)

Any help would be appreciated.

Thanks,

**Comment by KeitaMoromizato** [comment]
It looks like you created issue in wrong repository.
https://github.com/KeitaMoromizato/mysql-to-bigquery
